export const SEO_CONFIG = {
  default: {
    title: "CampusClip",
    description: "CampusClip — your all-in-one campus social platform for clubs, classes, events, and student connections.",
    keywords: "campus social, student clubs, college events, class management, campus networking, student community",
    ogImage: "https://campusclip.com/og-image.png",
  },
  home: {
    title: "CampusClip",
    description: "Connect with student clubs, manage classes, discover campus events, and build your campus community on CampusClip.",
    keywords: "campus social network, student clubs, college events, class scheduling, student networking",
    canonical: "/",
    ogType: "website",
  },
  login: {
    title: "Login",
    description: "Sign in to your CampusClip account to access your campus social network, manage classes, and connect with peers.",
    keywords: "login, sign in, campus social network",
    canonical: "/login",
    ogType: "website",
  },
  signup: {
    title: "Sign Up",
    description: "Create your CampusClip account to join your campus community, explore clubs, manage classes, and connect with students.",
    keywords: "sign up, registration, create account, student social network",
    canonical: "/signup",
    ogType: "website",
  },
  forgotPassword: {
    title: "Forgot Password",
    description: "Reset your CampusClip password. Enter your email to receive password recovery instructions.",
    keywords: "forgot password, password reset",
    canonical: "/forgot-password",
    noindex: true,
  },
  otpVerify: {
    title: "Verify OTP",
    description: "Verify your email address with a one-time password to complete your CampusClip registration.",
    keywords: "otp verification, email verification",
    canonical: "/otp-verify",
    noindex: true,
  },
  setPassword: {
    title: "Set Password",
    description: "Set a secure password for your CampusClip account.",
    keywords: "set password, account security",
    canonical: "/set-password",
    noindex: true,
  },
  dashboard: {
    title: "Dashboard",
    description: "View your campus dashboard with class schedules, grades, upcoming events, and campus news on CampusClip.",
    keywords: "dashboard, class schedule, grades, campus overview",
    canonical: "/dashboard",
  },
  feed: {
    title: "Campus Feed",
    description: "Explore posts, events, and updates from your campus community on CampusClip.",
    keywords: "campus feed, social posts, campus news, events",
    canonical: "/feed",
  },
  clubs: {
    title: "Campus Clubs",
    description: "Browse and join student clubs at your university. Discover new communities and connect with peers on CampusClip.",
    keywords: "student clubs, club directory, join clubs, campus organizations",
    canonical: "/clubs",
  },
  search: {
    title: "Search",
    description: "Search students, clubs, classes, and more on CampusClip. Find and connect with your campus community.",
    keywords: "search, student search, club search, class search",
    canonical: "/search",
  },
  searchClasses: {
    title: "All Classes",
    description: "Browse and filter all available classes on CampusClip. Find courses that match your academic interests.",
    keywords: "classes, course search, academic courses, class directory",
    canonical: "/search/classes",
  },
  searchStudents: {
    title: "All Students",
    description: "Connect with students across your campus. Browse profiles and build your campus network on CampusClip.",
    keywords: "student directory, student profiles, campus network",
    canonical: "/search/students",
  },
  searchClubs: {
    title: "All Clubs",
    description: "Explore all student clubs and organizations at your university. Find clubs that match your interests.",
    keywords: "club directory, student organizations, campus clubs",
    canonical: "/search/clubs",
  },
  calendar: {
    title: "Calendar",
    description: "View and manage your campus events and class schedule on CampusClip. Never miss an important date.",
    keywords: "calendar, event calendar, class schedule, campus events",
    canonical: "/calendar",
  },
  notifications: {
    title: "Notifications",
    description: "View all your CampusClip notifications and stay updated with your campus community.",
    keywords: "notifications, campus alerts",
    canonical: "/notifications",
    noindex: true,
  },
  archive: {
    title: "Archive",
    description: "Access your archived posts and content on CampusClip.",
    keywords: "archive, archived posts",
    canonical: "/archive",
  },
  paymentSuccess: {
    title: "Payment Successful",
    description: "Your payment has been processed successfully. Thank you for registering for the event on CampusClip.",
    keywords: "payment success, event registration",
    canonical: "/events/payment-success",
    noindex: true,
  },
  paymentCancel: {
    title: "Payment Cancelled",
    description: "Your payment was cancelled. You can try again or explore other events on CampusClip.",
    keywords: "payment cancelled, event registration",
    canonical: "/events/payment-cancel",
    noindex: true,
  },
  profileSetup: {
    title: "Profile Setup",
    description: "Set up your CampusClip profile to get started on your campus social journey.",
    keywords: "profile setup, onboarding",
    canonical: "/profile-setup",
    noindex: true,
  },
  selectClassCount: {
    title: "Select Classes",
    description: "Select the number of classes you're taking to personalize your CampusClip experience.",
    keywords: "class selection, onboarding",
    canonical: "/select-class-count",
    noindex: true,
  },
  addClasses: {
    title: "Add Classes",
    description: "Add your classes to your CampusClip account to connect with classmates and stay organized.",
    keywords: "add classes, class registration",
    canonical: "/add-classes",
    noindex: true,
  },
};

export const getMetadata = (configKey) => {
  return SEO_CONFIG[configKey] || SEO_CONFIG.default;
};
